export const GENERATE_ADVICE = 'ACTION_GENERATE_ADVICE';

export const GENERATE_ADVICE_SUCCEEDED = 'ACTION_GENERATE_ADVICE_SUCCEEDED';

export const GENERATE_ADVICE_FAILED = 'ACTION_GENERATE_ADVICE_FAILED';
